# For more info, see: https://supabase.com/docs/guides/cli/config
project_id = "findmybiz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true

[db.seed]
enabled = true
sql_paths = ["./seed/001_provinces_districts.sql", "./seed/002_cities.sql", "./seed/003_suburbs.sql", "./seed/004_categories.sql"]

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[auth.email]
enable_signup = true
enable_confirmations = true

[storage]
enabled = true
file_size_limit = "10MiB"
